Document: cdos-picturebrowser
Title: Debian cdos-picturebrowser Manual
Author: <insert document author here>
Abstract: This manual describes what cdos-picturebrowser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cdos-picturebrowser/cdos-picturebrowser.sgml.gz

Format: postscript
Files: /usr/share/doc/cdos-picturebrowser/cdos-picturebrowser.ps.gz

Format: text
Files: /usr/share/doc/cdos-picturebrowser/cdos-picturebrowser.text.gz

Format: HTML
Index: /usr/share/doc/cdos-picturebrowser/html/index.html
Files: /usr/share/doc/cdos-picturebrowser/html/*.html
